import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import Banner from '../components/Banner';
import ProductFeed from '../components/ProductFeed';
import { IProduct } from '../interfaces';

interface IHomePageProps {
  productsFromApi: IProduct[];
}

const Home: NextPage<IHomePageProps> = ({ productsFromApi }) => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="mx-auto max-w-screen-2xl">
        {/* Banner */}
        <Banner />

        {/* Product Feed */}
        <ProductFeed products={productsFromApi} />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async (context) => {
  try {
    const productsFromApi: Array<IProduct> = await (
      await fetch('https://fakestoreapi.com/products')
    ).json();

    return {
      props: {
        productsFromApi,
      },
    };
  } catch (err) {
    return { props: { productsFromApi: [] } };
  }
};
