import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import Banner from '../components/Banner';

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="mx-auto max-w-screen-2xl">
        {/* Banner */}
        <Banner />

        {/* Product Feed */}
      </main>
    </div>
  );
};

export default Home;
